version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.3
commands:
  install-deps:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - install-deps
      - run:
          name: Lint via ESLint
          command: yarn lint
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - install-deps
      - run:
          name: Run Tests
          command: yarn test
      - codecov/upload:
          file: coverage/coverage-final.json
workflows:
  lint+test:
    jobs:
      - lint
      - test
