version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.3
jobs:
  install-deps:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --freeze-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint via ESLint
          command: yarn lint
  test:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: yarn test
      - codecov/upload:
          file: coverage/coverage-final.json
  build:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish
          command: NPM_AUTH_TOKEN=$AUTH_TOKEN yarn publish --ignore-scripts --no-git-tag-version --registry $REGISTRY
workflows:
  lint-deploy:
    jobs:
      - install-deps:
          filters: &tags-filters
            tags:
              only: /^v\d+\.\d+\.\d+.*/
      - lint:
          filters:
            <<: *tags-filters
          requires:
            - install-deps
      - test:
          filters:
            <<: *tags-filters
          requires:
            - install-deps
      - build:
          filters: &version-filters
            <<: *tags-filters
            branches:
              ignore: /./
          requires:
            - lint
            - test
      - publish:
          filters:
            <<: *tags-filters
          requires:
            - build
          context:
            - npm-registry
